In [1]:
import numpy as np

In [2]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [3]:
def sigmoid_derivative(x):
  return x*(1-x)

In [4]:
X= np.array([[0,0],
             [0,1],
             [1,0],
             [1,1]])

In [5]:
y=np.array([[0],[1],[1],[0]])

In [6]:
np.random.seed(42)
input_size = 2
hidden_size = 2
output_size = 1
learning_rate = 0.1
epochs = 10000

In [7]:
w1= np.random.uniform(size=(input_size, hidden_size))
b1= np.random.uniform(size=(1, hidden_size))

w2= np.random.uniform(size=(hidden_size, output_size))
b2= np.random.uniform(size=(1, output_size))

In [8]:
for epoch in range(epochs):
  z1 = np.dot(X, w1) + b1
  a1 = sigmoid(z1)

  z2= np.dot(a1, w2) + b2
  a2 = sigmoid(z2)

  error = a2-y

  #backpropogration
  d_output = error * sigmoid_derivative(a2)   #dL/dz2
  error_hidden = d_output.dot(w2.T)   #dL/da1
  d_hidden = error_hidden * sigmoid_derivative(a1)    #dL/dz1


  d_w2 = a1.T.dot(d_output)   #dL/dw2 = dL/dz2 * dz2/dw2
  d_b2 = np.sum(d_output, axis=0, keepdims=True)  #dL/db2 = sigma(dL/dz2)


  d_w1 = X.T.dot(d_hidden)    #dL/dw1 = dL/da1 * da1/dz1
  d_b1 = np.sum(d_hidden, axis=0, keepdims=True)    #dL/db1 = sigma(dL/da1)

  w2 -= learning_rate*d_w2
  b2 -= learning_rate*d_b2
  w1 -= learning_rate*d_w1
  b1 -= learning_rate*d_b1

In [9]:
print("\nFinal Predictions:")
print(f"Targets: \n{y.T}")
print(f"Predicted: \n{a2.T}")
print(f"Binary Prediction: \n{np.round(a2).T}")


Final Predictions:
Targets: 
[[0 1 1 0]]
Predicted: 
[[0.05322146 0.95171535 0.95160449 0.05175396]]
Binary Prediction: 
[[0. 1. 1. 0.]]
